# Generated by Django 6.0.5 on 2026-06-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_programa_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
