# Generated by Django 6.0.5 on 2026-06-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auspiciador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='auspiciadores/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_programa', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('horario', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('alumnos', models.ManyToManyField(related_name='programas', to='alumnos.alumno')),
            ],
        ),
    ]
