# Generated by Django 6.0.5 on 2026-06-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('rival', models.CharField(max_length=100)),
                ('resultado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField()),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
