# Generated by Django 6.0.5 on 2026-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estado_inscripcion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
