# Generated by Django 6.0.5 on 2026-06-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('entrenamiento', 'Entrenamiento'), ('partido', 'Partido'), ('reunion', 'Reunión')], max_length=50)),
            ],
        ),
    ]
