# Generated by Django 6.0.5 on 2026-06-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('entrenamiento', 'Entrenamiento'), ('partido', 'Partido'), ('reunion', 'Reunión'), ('torneo', 'Torneo')], max_length=50),
        ),
    ]
