# Generated by Django 6.0.5 on 2026-06-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_pago_confirmado_alumno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='password_temporal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
