# Generated by Django 6.0.5 on 2026-06-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_password_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='metodo_envio',
            field=models.CharField(choices=[('correo', 'Correo electrónico'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='correo', max_length=10),
        ),
    ]
