# Generated by Django 6.0.5 on 2026-06-21 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_alumno_metodo_envio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='metodo_envio',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='password_temporal',
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado_inscripcion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
