# Generated by Django 6.0.5 on 2026-06-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], max_length=10)),
                ('url_archivo', models.URLField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
