# Generated by Django 6.0.5 on 2026-06-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url_archivo',
        ),
        migrations.AddField(
            model_name='media',
            name='url_original',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace de Google Drive'),
        ),
    ]
