# Generated by Django 6.0.5 on 2026-06-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_remove_media_url_archivo_media_url_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='galeria/'),
        ),
    ]
